example/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poker/', include('planning_poker.urls')),
]

planning_poker/urls.py
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'planning_poker'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.PokerSessionView.as_view(), name='poker_session'),
    path('jsi18n/',
         JavaScriptCatalog.as_view(packages=['planning_poker']),
         name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
]

planning_poker/models.py
from collections import OrderedDict, defaultdict
from typing import Dict, List

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from .constants import ALL_VOTING_OPTIONS, FIBONACCI_CHOICES

try:
    # The OrderedDict was added to the typing module in Python version 3.7.
    # Fall back to the default Dict type in order to provide backwards compatibility for Python 3.6.
    from typing import OrderedDict as OrderedDictType
except ImportError:  # pragma: no cover
    OrderedDictType = Dict


class PokerSession(models.Model):
    #: The date on which the poker session should take place.
    poker_date = models.DateField(verbose_name=_('Poker Date'))
    #: The poker session's name. Used for displaying it to the user.
    name = models.CharField(max_length=200, verbose_name=_('Name'))
    #: The story which is currently active in this poker session.
    active_story = models.OneToOneField(
        'Story',
        on_delete=models.SET_NULL,
        verbose_name=_('Active Story'),
        related_name='active_in',
        null=True
    )

    class Meta:
        ordering = ['-poker_date']
        verbose_name = _('Poker Session')
        verbose_name_plural = _('Poker Sessions')

    def __str__(self) -> str:
        return self.name


class Story(models.Model):
    #: The story's ticket number. Used for displaying the story to the user.
    ticket_number = models.CharField(max_length=200, verbose_name=_('Ticket Number'))
    #: The story's title. Used for displaying the story to the user.
    title = models.CharField(max_length=200, verbose_name=_('Title'), blank=True)
    #: The story's description. This is the main source of information for participants in a poker session.
    description = models.TextField(verbose_name=_('Description'), blank=True)
    #: The estimated story points. The value is either an element of
    #: :py:data:`planning_poker.constants.FIBONACCI_CHOICES` or ``None``.
    story_points = models.PositiveSmallIntegerField(
        verbose_name=_('Story Points'),
        help_text=_('The amount of points this story takes up in the sprint'),
        null=True,
        blank=True,
        choices=[(None, '-')] + [(int(number), label) for number, label in FIBONACCI_CHOICES]
    )
    #: The poker session to which this story belongs to.
    poker_session = models.ForeignKey(
        PokerSession, on_delete=models.SET_NULL,
        verbose_name=_('Poker Session'),
        related_name='stories',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = _('Story')
        verbose_name_plural = _('Stories')
        order_with_respect_to = 'poker_session'
        permissions = [
            ('vote', 'Can vote for a story.'),
            ('moderate', 'Is able to moderate a planning_poker session.'),
        ]

    def __str__(self) -> str:
        if self.title:
            return '{}: {}'.format(self.ticket_number, self.title)
        return self.ticket_number

    def get_votes_with_voter_information(self) -> OrderedDictType[str, List[Dict[str, str]]]:
        """Return a sorted list with each choice + the users who voted for that choice.

        :return: A sorted list with each choice + the users who voted for that choice.
        """
        votes = defaultdict(list)
        for vote in self.votes.select_related('user'):
            votes[vote.choice].append({'id': vote.user.id, 'name': vote.user.username})
        return OrderedDict(sorted(votes.items(), key=lambda vote: len(vote[1]), reverse=True))


class Vote(models.Model):
    #: The story for which this vote was casted for.
    story = models.ForeignKey(
        Story,
        on_delete=models.CASCADE,
        verbose_name=_('Story'),
        related_name='votes'
    )
    #: The user who casted the vote.
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('User'),
        related_name='votes'
    )
    #: The option which was voted for. See :py:data:`planning_poker.constants.ALL_VOTING_OPTIONS` for all possible
    #: values.
    choice = models.CharField(
        max_length=200,
        verbose_name=_('Choice'),
        choices=ALL_VOTING_OPTIONS
    )

    class Meta:
        verbose_name = _('Vote')
        verbose_name_plural = _('Votes')
        constraints = [
            models.UniqueConstraint(fields=['story', 'user'], name='A user can only vote once for each story.')
        ]

    def __str__(self) -> str:
        return _('{user} voted {choice} for story {story}').format(
            user=self.user,
            choice=self.get_choice_display(),
            story=self.story
        )

planning_poker/views.py
from typing import Any, Dict

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ImproperlyConfigured
from django.db.models import Count, Q
from django.shortcuts import resolve_url
from django.views.generic import DetailView, ListView

from .constants import FIBONACCI_CHOICES, NON_POINT_OPTIONS
from .models import PokerSession


class LoginLogoutMixin(LoginRequiredMixin):
    logout_url = None

    def get_logout_url(self) -> str:
        """
        Determine the logout URL which can be used by users to log out.

        :return: The URL which can be used by users to log out.
        """
        logout_url = self.logout_url or getattr(settings, 'LOGOUT_URL', None)
        if not logout_url:
            raise ImproperlyConfigured(
                '{0} is missing the logout_url attribute. Define {0}.logout_url, settings.LOGOUT_URL, or override '
                '{0}.get_logout_url().'.format(self.__class__.__name__)
            )
        return resolve_url(logout_url)

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['logout_url'] = self.get_logout_url()
        return context


class PokerSessionView(LoginLogoutMixin, DetailView):
    model = PokerSession
    template_name = 'planning_poker/poker_session.html'

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['options'] = {
            'point_options': [list(choice) for choice in FIBONACCI_CHOICES],
            'non_point_options': [list(choice) for choice in NON_POINT_OPTIONS]
        }
        context['stories'] = [
            {
                'id': story.id,
                'title': str(story),
                'points': str(story.story_points) if story.story_points else None
            } for story in self.object.stories.all()
        ]
        context['permissions'] = {
            'vote': self.request.user.has_perm('planning_poker.vote'),
            'moderate': self.request.user.has_perm('planning_poker.moderate')
        }
        return context


class IndexView(LoginLogoutMixin, ListView):
    queryset = PokerSession.objects.filter(stories__story_points__isnull=True).distinct().annotate(
        unpokered_stories=Count('id', filter=Q(stories__story_points__isnull=True))
    )
    template_name = 'planning_poker/index.html'

planning_poker/templates/planning_poker/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'planning_poker/css/poker.css' %}">

    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'planning_poker/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'planning_poker/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'planning_poker/favicons/favicon-16x16.png' %}">
    <link rel="mask-icon" href="{% static 'planning_poker/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
    <link rel="shortcut icon" href="{% static 'planning_poker/favicons/favicon.ico' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    {% block css %}{% endblock %}
</head>
<body>
<div id="app">
    {% block navbar %}
        <navbar>
            <template v-slot:brand>
                <a href="{% url 'planning_poker:index' %}"><h2 class="brand">{% trans "Poker Sessions" %}</h2></a>
                <span>{% block navtitle %}{% endblock %}</span>
                {% block brandslot %}{% endblock %}
            </template>
            <template v-slot:nav>
                {% block logged-in-as %}
                    <span class="navbar-text pr-1">{% trans "You are logged in as" %}
                        <span class="text-info">{{ user }}</span>
                    </span>
                {% endblock logged-in-as %}
                <span class="user-function">
                    {% block admin-link %}
                        {% if user.is_staff %}
                            <a class="nav-link" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
                        {% endif %}
                    {% endblock admin-link %}
                    {% block logout-link %}
                        <a class="nav-link" href="{{ logout_url }}">{% trans 'Logout' %}</a>
                    {% endblock logout-link %}
                    {% block set-language %}
                        <form action="{% url 'planning_poker:set_language' %}" method="post">{% csrf_token %}
                            <input name="next" type="hidden" value=".">
                            <select name="language" onchange="this.form.submit()">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                        {{ language.name_local }} ({{ language.code }})
                                    </option>
                                {% endfor %}
                            </select>
                        </form>
                    {% endblock set-language %}
                    {% block additional-user-functions %}{% endblock additional-user-functions %}
                </span>
            </template>
        </navbar>
    {% endblock navbar %}
    {% block content %}{% endblock content %}
</div>

{% block js %}{% endblock %}
{% block vue-app %}
<script type="module" src="{% static 'planning_poker/js/header-app.js' %}"></script>
{% endblock %}
</body>
</html>

planning_poker/templates/planning_poker/index.html
{% extends 'planning_poker/base.html' %}
{% load i18n humanize %}


{% block title %}
    {% trans 'Choose your Poker Session' %}
{% endblock title %}

{% block content %}
    <div class="centered-flex">
        <h1>{% trans 'Active Sessions' %}</h1>
        {% for poker_session in object_list %}
            <a href="{% url 'planning_poker:poker_session' poker_session.id %}"
               class="poker-session-row">
                <div>
                    <h5 class="ellipsis-overflow">{{ poker_session }}</h5>
                    <span>
                        {% blocktrans trimmed count unpokered_stories=poker_session.unpokered_stories %}
                            {{ unpokered_stories }} ticket left to poker
                        {% plural %}
                            {{ unpokered_stories }} tickets left to poker
                        {% endblocktrans %}
                    </span>
                </div>
                <small>{{ poker_session.poker_date|naturalday }}</small>
            </a>
        {% endfor %}
    </div>
{% endblock content %}

planning_poker/templates/planning_poker/poker_session.html
{% extends 'planning_poker/base.html' %}
{% load i18n static %}

{% block title %}
{% blocktrans %}Poker Session: {{ pokersession }}{% endblocktrans %}
{% endblock title %}

{% block navtitle %}
{{ pokersession }}
{% endblock navtitle %}

{% block brandslot %}
<participants-list ref="participantsList">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M7.5 6.5C7.5 8.981 9.519 11 12 11s4.5-2.019 4.5-4.5S14.481 2 12 2 7.5 4.019 7.5 6.5zM20 21h1v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h1 1 14H20z"/></svg>
</participants-list>
{% endblock %}

{% block content %}
<poker-site></poker-site>
{% endblock content %}

{% block js %}
{{ options|json_script:"options" }}
{{ stories|json_script:"initial-stories" }}
{{ permissions|json_script:"permissions" }}
{{ request.get_host|json_script:"host" }}
{{ pokersession.id|json_script:"pokersession-id" }}
{{ user.id|json_script:"user-id" }}
<script type="text/javascript" src="{% url 'planning_poker:javascript-catalog' %}"></script>
{% endblock js %}

{% block vue-app %}
<script type="module" src="{% static 'planning_poker/js/poker-session.js' %}"></script>
{% endblock %}